// =========================================
// DATABASE & TEMA (TERPISAH)
// =========================================
const themeDatabase = {
    minecraft: {
        bg: 'themes/minecraft/images/main_bg.png',
        body_bg: 'themes/minecraft/images/body_bg.jpg',
        info_bg: 'themes/minecraft/images/info_bg.jpg',
        vip: 'themes/minecraft/images/vip_bg.png',
		bottom_bg: 'themes/minecraft/images/bottom_bg.png',
        
        // Generated normal_items
        normal_items: [
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (1).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (2).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (3).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (4).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (5).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (6).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (7).gif" },
            { name: "ALLAY", rarity: "common", img: "themes/minecraft/images/Common/Allay (8).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (1).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (10).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (11).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (12).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (13).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (14).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (15).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (16).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (17).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (2).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (3).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (4).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (5).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (6).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (7).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (8).gif" },
            { name: "ARMADILLO", rarity: "common", img: "themes/minecraft/images/Common/Armadillo (9).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (1).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (10).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (11).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (12).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (13).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (14).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (15).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (16).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (17).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (18).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (19).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (2).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (20).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (21).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (22).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (23).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (24).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (25).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (26).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (27).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (28).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (29).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (3).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (30).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (31).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (32).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (33).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (34).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (35).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (36).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (37).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (38).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (39).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (4).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (40).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (41).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (42).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (43).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (44).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (45).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (46).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (47).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (48).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (49).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (5).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (50).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (51).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (6).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (7).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (8).gif" },
            { name: "AXOLOTL", rarity: "common", img: "themes/minecraft/images/Common/Axolotl (9).gif" },
            { name: "BABY ZOMBIE BLACKSMITH", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Blacksmith.png" },
            { name: "BABY ZOMBIE BUTCHER", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Butcher.png" },
            { name: "BABY ZOMBIE FARMER", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Farmer.png" },
            { name: "BABY ZOMBIE LIBRARIAN", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Librarian.png" },
            { name: "BABY ZOMBIE NITWIT", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Nitwit.png" },
            { name: "BABY ZOMBIE PRIEST", rarity: "common", img: "themes/minecraft/images/Common/Baby Zombie Priest.png" },
            { name: "BALLOON BUNDLE (TRAILS AND TALES SUMMER EVENT) INTERACT ANIMATION", rarity: "common", img: "themes/minecraft/images/Common/Balloon Bundle (Trails and Tales Summer Event) Interact Animation.gif" },
            { name: "BAT", rarity: "common", img: "themes/minecraft/images/Common/Bat (1).gif" },
            { name: "BAT", rarity: "common", img: "themes/minecraft/images/Common/Bat (2).gif" },
            { name: "BAT", rarity: "common", img: "themes/minecraft/images/Common/Bat (3).gif" },
            { name: "BAT", rarity: "common", img: "themes/minecraft/images/Common/Bat (4).gif" },
            { name: "BEAR", rarity: "common", img: "themes/minecraft/images/Common/Bear.gif" },
            { name: "BEAR", rarity: "common", img: "themes/minecraft/images/Common/Bear.png" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (1).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (10).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (11).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (12).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (13).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (14).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (15).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (16).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (17).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (18).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (19).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (2).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (20).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (21).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (22).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (23).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (24).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (25).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (26).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (27).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (28).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (29).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (3).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (4).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (5).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (6).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (7).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (8).gif" },
            { name: "BEE", rarity: "common", img: "themes/minecraft/images/Common/Bee (9).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (1).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (2).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (3).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (4).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (5).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (6).gif" },
            { name: "BLAZE", rarity: "common", img: "themes/minecraft/images/Common/Blaze (7).gif" },
            { name: "BREEZE", rarity: "common", img: "themes/minecraft/images/Common/Breeze.gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (1).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (10).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (11).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (12).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (13).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (14).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (2).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (3).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (4).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (5).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (6).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (7).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (8).gif" },
            { name: "BUNNY", rarity: "common", img: "themes/minecraft/images/Common/Bunny (9).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (1).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (10).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (11).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (12).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (13).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (14).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (15).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (16).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (17).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (18).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (19).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (2).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (20).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (21).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (3).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (4).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (5).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (6).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (7).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (8).gif" },
            { name: "CAMEL", rarity: "common", img: "themes/minecraft/images/Common/Camel (9).gif" },
            { name: "CAT", rarity: "common", img: "themes/minecraft/images/Common/Cat.gif" },
            { name: "CHICKEN JOCKEY", rarity: "common", img: "themes/minecraft/images/Common/Chicken Jockey.gif" },
            { name: "CHICKEN", rarity: "common", img: "themes/minecraft/images/Common/Chicken.gif" },
            { name: "COD BE", rarity: "common", img: "themes/minecraft/images/Common/Cod BE.gif" },
            { name: "COD", rarity: "common", img: "themes/minecraft/images/Common/Cod.gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (1).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (11).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (12).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (13).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (14).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (15).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (16).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (17).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (18).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (19).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (20).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (21).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (22).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (23).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (24).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (25).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (26).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (27).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (28).gif" },
            { name: "COPPER GOLEM", rarity: "common", img: "themes/minecraft/images/Common/Copper Golem (29).gif" },
            { name: "CORAL ZOMBIE NAUTILUS BREATHE JE1", rarity: "common", img: "themes/minecraft/images/Common/Coral Zombie Nautilus Breathe JE1.gif" },
            { name: "CREEPER", rarity: "common", img: "themes/minecraft/images/Common/Creeper (2).gif" },
            { name: "CREEPER", rarity: "common", img: "themes/minecraft/images/Common/Creeper.gif" },
            { name: "DOLPHIN", rarity: "common", img: "themes/minecraft/images/Common/Dolphin (1).gif" },
            { name: "DOLPHIN", rarity: "common", img: "themes/minecraft/images/Common/Dolphin (2).gif" },
            { name: "DOLPHIN", rarity: "common", img: "themes/minecraft/images/Common/Dolphin.gif" },
            { name: "ENDERMITE", rarity: "common", img: "themes/minecraft/images/Common/Endermite (1).gif" },
            { name: "ENDERMITE", rarity: "common", img: "themes/minecraft/images/Common/Endermite.gif" },
            { name: "EVOKER", rarity: "common", img: "themes/minecraft/images/Common/Evoker.gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (1).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (2).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (3).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (4).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (5).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (6).gif" },
            { name: "FISH", rarity: "common", img: "themes/minecraft/images/Common/Fish (7).gif" },
            { name: "FOX", rarity: "common", img: "themes/minecraft/images/Common/Fox.png" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (1).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (10).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (11).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (12).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (13).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (14).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (15).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (2).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (3).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (4).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (5).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (6).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (7).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (8).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog (9).gif" },
            { name: "FROG", rarity: "common", img: "themes/minecraft/images/Common/Frog.gif" },
            { name: "FROG1", rarity: "common", img: "themes/minecraft/images/Common/Frog1.gif" },
            { name: "FROG2", rarity: "common", img: "themes/minecraft/images/Common/Frog2.gif" },
            { name: "FROG4", rarity: "common", img: "themes/minecraft/images/Common/Frog4.gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (1).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (10).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (11).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (12).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (13).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (14).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (15).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (16).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (17).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (18).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (19).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (2).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (20).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (21).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (22).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (23).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (24).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (25).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (26).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (27).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (28).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (29).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (3).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (30).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (31).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (32).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (33).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (34).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (35).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (36).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (37).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (38).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (39).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (4).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (40).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (41).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (42).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (43).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (44).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (45).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (46).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (47).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (48).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (49).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (5).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (6).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (7).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (8).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast (9).gif" },
            { name: "GHAST", rarity: "common", img: "themes/minecraft/images/Common/Ghast.gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (1).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (2).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (3).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (4).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (5).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (6).gif" },
            { name: "GLOW SQUID", rarity: "common", img: "themes/minecraft/images/Common/Glow Squid (7).gif" },
            { name: "GOAT", rarity: "common", img: "themes/minecraft/images/Common/Goat (1).gif" },
            { name: "GOAT", rarity: "common", img: "themes/minecraft/images/Common/Goat (2).gif" },
            { name: "GOAT", rarity: "common", img: "themes/minecraft/images/Common/Goat.gif" },
            { name: "GUARDIAN JE2 BE2", rarity: "common", img: "themes/minecraft/images/Common/Guardian JE2 BE2.gif" },
            { name: "GUARDIAN TAILFIN CHANGE 21W11A", rarity: "common", img: "themes/minecraft/images/Common/Guardian tailfin change 21w11a.gif" },
            { name: "GUARDIAN", rarity: "common", img: "themes/minecraft/images/Common/Guardian.gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (1).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (10).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (11).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (12).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (5).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (6).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (7).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (8).gif" },
            { name: "HOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Hoglin (9).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (1).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (10).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (11).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (12).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (13).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (14).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (15).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (16).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (17).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (18).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (19).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (2).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (20).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (21).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (22).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (23).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (24).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (25).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (26).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (27).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (28).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (29).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (3).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (30).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (31).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (32).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (33).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (34).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (35).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (36).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (37).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (38).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (39).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (4).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (40).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (41).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (42).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (43).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (44).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (45).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (5).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (6).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (7).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (8).gif" },
            { name: "HORSE", rarity: "common", img: "themes/minecraft/images/Common/Horse (9).gif" },
            { name: "ILLUSIONER CELEBRATING", rarity: "common", img: "themes/minecraft/images/Common/Illusioner celebrating.gif" },
            { name: "JUMPING GOAT ANIMATION (PIXEL ART)", rarity: "common", img: "themes/minecraft/images/Common/Jumping goat animation (pixel art).gif" },
            { name: "KILLER BUNNY HEAD TILT", rarity: "common", img: "themes/minecraft/images/Common/Killer bunny head tilt.gif" },
            { name: "KILLER BUNNY MOVE", rarity: "common", img: "themes/minecraft/images/Common/Killer bunny move.gif" },
            { name: "LLAMA", rarity: "common", img: "themes/minecraft/images/Common/LLama.png" },
            { name: "MAGMA CUBE", rarity: "common", img: "themes/minecraft/images/Common/Magma Cube.gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (1).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (10).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (11).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (12).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (13).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (14).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (15).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (16).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (17).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (18).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (19).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (2).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (20).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (21).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (22).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (3).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (4).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (5).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (6).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (8).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus (9).gif" },
            { name: "NAUTILUS", rarity: "common", img: "themes/minecraft/images/Common/Nautilus.gif" },
            { name: "OXIDIZED COPPER GOLEM SPAWN JE1 BE1", rarity: "common", img: "themes/minecraft/images/Common/Oxidized copper golem spawn JE1 BE1.gif" },
            { name: "PANDA", rarity: "common", img: "themes/minecraft/images/Common/Panda (1).gif" },
            { name: "PANDA", rarity: "common", img: "themes/minecraft/images/Common/Panda (2).gif" },
            { name: "PANDA", rarity: "common", img: "themes/minecraft/images/Common/Panda (3).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (1).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (2).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (3).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (4).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (5).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (6).gif" },
            { name: "PARROT", rarity: "common", img: "themes/minecraft/images/Common/Parrot (7).gif" },
            { name: "PARROT STICKER", rarity: "common", img: "themes/minecraft/images/Common/Parrot Sticker.gif" },
            { name: "PHANTOM", rarity: "common", img: "themes/minecraft/images/Common/Phantom (1).gif" },
            { name: "PHANTOM", rarity: "common", img: "themes/minecraft/images/Common/Phantom (2).gif" },
            { name: "PHANTOM", rarity: "common", img: "themes/minecraft/images/Common/Phantom (3).gif" },
            { name: "PHANTOM", rarity: "common", img: "themes/minecraft/images/Common/Phantom (4).gif" },
            { name: "PIG", rarity: "common", img: "themes/minecraft/images/Common/Pig.gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (1).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (2).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (3).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (4).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (5).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (6).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin (7).gif" },
            { name: "PIGLIN", rarity: "common", img: "themes/minecraft/images/Common/Piglin.gif" },
            { name: "PILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Pillager (1).gif" },
            { name: "PILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Pillager (2).gif" },
            { name: "PILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Pillager (3).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (1).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (2).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (3).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (4).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (5).gif" },
            { name: "PUFFERFISH", rarity: "common", img: "themes/minecraft/images/Common/Pufferfish (6).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (1).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (2).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (3).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (4).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (5).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (6).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (7).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit (8).gif" },
            { name: "RABBIT", rarity: "common", img: "themes/minecraft/images/Common/Rabbit.gif" },
            { name: "RAVAGER", rarity: "common", img: "themes/minecraft/images/Common/Ravager (1).gif" },
            { name: "RAVAGER", rarity: "common", img: "themes/minecraft/images/Common/Ravager (2).gif" },
            { name: "RAVAGER", rarity: "common", img: "themes/minecraft/images/Common/Ravager (3).gif" },
            { name: "RAVAGER", rarity: "common", img: "themes/minecraft/images/Common/Ravager (4).gif" },
            { name: "SALMON", rarity: "common", img: "themes/minecraft/images/Common/Salmon (2).gif" },
            { name: "SALMON", rarity: "common", img: "themes/minecraft/images/Common/Salmon.gif" },
            { name: "SHEEP", rarity: "common", img: "themes/minecraft/images/Common/Sheep (1).gif" },
            { name: "SHEEP", rarity: "common", img: "themes/minecraft/images/Common/Sheep (2).gif" },
            { name: "SHEEP", rarity: "common", img: "themes/minecraft/images/Common/Sheep (3).gif" },
            { name: "SHULKER", rarity: "common", img: "themes/minecraft/images/Common/Shulker.png" },
            { name: "SILVERFISH", rarity: "common", img: "themes/minecraft/images/Common/Silverfish (1).gif" },
            { name: "SILVERFISH", rarity: "common", img: "themes/minecraft/images/Common/Silverfish (2).gif" },
            { name: "SLIME", rarity: "common", img: "themes/minecraft/images/Common/Slime.png" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (1).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (10).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (11).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (13).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (14).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (15).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (16).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (17).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (18).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (19).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (2).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (3).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (4).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (5).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (6).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (7).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (8).gif" },
            { name: "SNIFFER", rarity: "common", img: "themes/minecraft/images/Common/Sniffer (9).gif" },
            { name: "SQUID JE2 BE2", rarity: "common", img: "themes/minecraft/images/Common/Squid JE2 BE2.gif" },
            { name: "SQUID MP", rarity: "common", img: "themes/minecraft/images/Common/Squid MP.gif" },
            { name: "SQUID STICKER", rarity: "common", img: "themes/minecraft/images/Common/Squid Sticker.gif" },
            { name: "SQUID", rarity: "common", img: "themes/minecraft/images/Common/Squid.gif" },
            { name: "STALKER TRANSFORM", rarity: "common", img: "themes/minecraft/images/Common/Stalker transform.gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (1).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (10).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (11).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (12).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (13).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (14).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (15).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (16).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (17).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (18).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (19).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (2).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (20).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (21).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (22).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (23).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (24).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (25).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (26).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (3).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (4).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (5).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (6).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (7).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (8).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider (9).gif" },
            { name: "STRIDER", rarity: "common", img: "themes/minecraft/images/Common/Strider.gif" },
            { name: "TADPOLE", rarity: "common", img: "themes/minecraft/images/Common/Tadpole (1).gif" },
            { name: "TADPOLE", rarity: "common", img: "themes/minecraft/images/Common/Tadpole (2).gif" },
            { name: "TINY FROGS DANCE MOB VOTE SERVER", rarity: "common", img: "themes/minecraft/images/Common/Tiny Frogs Dance Mob Vote Server.gif" },
            { name: "TROPICAL FROG WALKING", rarity: "common", img: "themes/minecraft/images/Common/Tropical Frog Walking.gif" },
            { name: "VEX", rarity: "common", img: "themes/minecraft/images/Common/Vex (1).gif" },
            { name: "VEX", rarity: "common", img: "themes/minecraft/images/Common/Vex (2).gif" },
            { name: "VEX", rarity: "common", img: "themes/minecraft/images/Common/Vex (3).gif" },
            { name: "VEX", rarity: "common", img: "themes/minecraft/images/Common/Vex (4).gif" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (1).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (10).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (11).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (12).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (13).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (14).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (15).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (16).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (17).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (18).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (19).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (2).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (20).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (21).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (22).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (23).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (24).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (25).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (26).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (3).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (4).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (5).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (6).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (7).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (8).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager (9).png" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager.gif" },
            { name: "VILLAGER", rarity: "common", img: "themes/minecraft/images/Common/Villager.png" },
            { name: "VINDICATOR", rarity: "common", img: "themes/minecraft/images/Common/Vindicator.gif" },
            { name: "ZOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Zoglin (1).gif" },
            { name: "ZOGLIN", rarity: "common", img: "themes/minecraft/images/Common/Zoglin (2).gif" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (1).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (10).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (11).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (12).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (13).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (14).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (15).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (16).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (17).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (18).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (19).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (2).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (20).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (21).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (22).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (23).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (24).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (25).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (26).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (27).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (28).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (29).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (3).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (30).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (32).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (33).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (34).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (35).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (36).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (37).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (38).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (4).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (5).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (6).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (7).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (8).png" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie (9).png" },
            { name: "ZOMBIE BECOMING DROWNED", rarity: "common", img: "themes/minecraft/images/Common/Zombie becoming Drowned.gif" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie.gif" },
            { name: "ZOMBIE", rarity: "common", img: "themes/minecraft/images/Common/Zombie.png" }
        ],

        // Generated vip_items
        vip_items: [
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (1).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (2).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (3).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (4).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (5).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (6).gif" },
            { name: "CREACKING", rarity: "legendary", img: "themes/minecraft/images/Rare/Creacking (7).gif" },
            { name: "ELDER GUARDIAN", rarity: "legendary", img: "themes/minecraft/images/Rare/Elder Guardian (1).gif" },
            { name: "ELDER GUARDIAN", rarity: "legendary", img: "themes/minecraft/images/Rare/Elder Guardian (2).gif" },
            { name: "ENDER DRAGON", rarity: "legendary", img: "themes/minecraft/images/Rare/Ender Dragon.gif" },
            { name: "ENDERMAN", rarity: "legendary", img: "themes/minecraft/images/Rare/Enderman.gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (1).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (10).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (11).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (12).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (13).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (2).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (3).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (4).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (5).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (6).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (7).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (8).gif" },
            { name: "WARDEN", rarity: "legendary", img: "themes/minecraft/images/Rare/Warden (9).gif" }
        ],



    },
    primbon: {
        bg: 'themes/primbon/images/main_bg.png',
        body_bg: 'themes/primbon/images/body_bg.jpg',
        info_bg: 'themes/primbon/images/info_bg.jpg',
        vip: 'themes/primbon/images/vip_bg.png',
        normal_items: [
            { name: "TUTUP PANCI", rarity: "common", img: "themes/primbon/images/normal/panci.png" },
            { name: "SAPU LIDI", rarity: "rare", img: "themes/primbon/images/normal/sapu.png" }
        ],
        vip_items: [
            { name: "MACAN PUTIH", rarity: "legendary", img: "themes/primbon/images/vip/macan.png" },
            { name: "NAGA BUMI", rarity: "legendary", img: "themes/primbon/images/vip/naga.png" }
        ]
    }
};